version: '2'
services:
  db:
    image: mariadb:10.1
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      # - ./wordpress/wp-content:/var/www/html/wp-content
      # - ./wordpress/wp-content/uploads:/var/www/wp-content/uploads
    links:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: http://localhost
      FS_METHOD: direct